create or replace PACKAGE UTILS_USERS_LOG IS 

    PROCEDURE GET_USERS_LOG_BY_USER_ID(P_USER_ID USERS_LOG.USER_ID%TYPE);

    PROCEDURE GET_USERS_LOG_BY_UPDATED_DATE(P_UPDATED_DATE DATE);

    PROCEDURE GET_USERS_LOG_BY_DATE_RANGE(P_FROM_UPDATED_DATE DATE, P_TO_UPDATED_DATE DATE);

    PROCEDURE DISPLAY_USERS_LOG;

END UTILS_USERS_LOG;
/