create or replace PACKAGE BANK_PKG
IS

    FUNCTION CHECK_NULLS_ADD_BANK_BRANCH 
    (
        P_BANK_NAME_	BANK.BANK_NAME%TYPE,
        P_IFSC_CODE_	BANK.IFSC_CODE%TYPE,
        P_BRANCH_NAME_	BANK.BRANCH_NAME%TYPE,
        P_BUILDING_NUMBER_	BANK.BUILDING_NUMBER%TYPE,
        P_STREET_	BANK.STREET%TYPE,
        P_CITY_	BANK.CITY%TYPE,
        P_PINCODE_ BANK.PINCODE%TYPE,
        P_DISTRICT_	BANK.DISTRICT%TYPE,
        P_STATE_	BANK.STATE%TYPE,
        P_COUNTRY_	 BANK.COUNTRY%TYPE
    )
        RETURN BOOLEAN;
    FUNCTION CHECK_BANK_BRANCH_NAME_EXISTS(P_BRANCH_NAME IN OUT  BANK.BRANCH_NAME%TYPE) RETURN BOOLEAN;
    FUNCTION CHECK_IFSC_EXISTS(P_IFSCCODE BANK.IFSC_CODE%TYPE) RETURN BOOLEAN;
    FUNCTION VALID_IFSC(P_IFSC_CODE IN VARCHAR2) RETURN BOOLEAN;
    FUNCTION VALIDATE_PINCODE(P_PIN_CODE BANK.PINCODE%TYPE) RETURN NUMBER;
    PROCEDURE ADD_BANK_BRANCH
    (
        P_BANK_NAME	BANK.BANK_NAME%TYPE,
     	P_IFSC_CODE	BANK.IFSC_CODE%TYPE,
     	P_BRANCH_NAME	BANK.BRANCH_NAME%TYPE,
     	P_BUILDING_NUMBER	BANK.BUILDING_NUMBER%TYPE,
     	P_STREET	BANK.STREET%TYPE,
     	P_CITY	BANK.CITY%TYPE,
     	P_PINCODE BANK.PINCODE%TYPE,
     	P_DISTRICT	BANK.DISTRICT%TYPE,
     	P_STATE	BANK.STATE%TYPE,
     	P_COUNTRY	 BANK.COUNTRY%TYPE
    );
END BANK_PKG;
/