create or replace TRIGGER ADD_FAILED_ATTEMPT_TRIGGER_GET_ACCCOUNT
BEFORE INSERT OR UPDATE ON FAILED_LOGIN_ATTEMPTS
FOR EACH ROW
DECLARE
BEGIN
    FAILED_ATTEMPTS.V_ACCOUNT_ID := :NEW.ACCOUNT_ID;
END;
/