create or replace TRIGGER ADD_FAILED_ATTEMPT_TRIGGER
AFTER INSERT OR UPDATE ON FAILED_LOGIN_ATTEMPTS
DECLARE
    V_ACCOUNT_ID ACCOUNT.ACCOUNT_ID%TYPE;
    V_COUNT NUMBER := 0;
BEGIN
    SELECT FAILED_COUNT INTO V_COUNT FROM FAILED_LOGIN_ATTEMPTS WHERE ACCOUNT_ID = FAILED_ATTEMPTS.V_ACCOUNT_ID;
    IF V_COUNT > 2 THEN
        UPDATE ACCOUNT
        SET IS_LOCKED = 'Y'
        WHERE ACCOUNT_ID = FAILED_ATTEMPTS.V_ACCOUNT_ID;
        DBMS_OUTPUT.PUT_LINE('YOUR ACCOUNT ' || FAILED_ATTEMPTS.V_ACCOUNT_ID || ' IS LOCKED FOR MULTIPLE FAILED PASSWORD ATTEMPTS' );
    END IF;
END;
/