create or replace PACKAGE IDENTITY_INFO_PKG
IS
    FUNCTION CHECK_AADHAR_NUMBER_EXISTS_IN_IDENTITY_INFO
    (
        P_AADHAR_NUMBER_ IDENTITY_INFO.AADHAR_NUMBER%TYPE
    ) RETURN BOOLEAN;

    FUNCTION CHECK_PAN_NUMBER_EXISTS_IN_IDENTITY_INFO
    (
        P_PAN_NUMBER_ IDENTITY_INFO.PAN_NUMBER%TYPE
    ) RETURN BOOLEAN;

    FUNCTION CHECK_NULLS_ADD_IDENTITY_INFO
    (
        FULL_NAME_ IDENTITY_INFO.IDENTITY_ID%TYPE,
        AADHAR_NUMBER_ IDENTITY_INFO.AADHAR_NUMBER%TYPE,
        PAN_NUMBER_ IDENTITY_INFO.PAN_NUMBER%TYPE
    )
    RETURN BOOLEAN;

    PROCEDURE ADD_IDENTITY_INFO
    (
        P_FULL_NAME IDENTITY_INFO.IDENTITY_ID%TYPE,
        P_AADHAR_NUMBER IDENTITY_INFO.AADHAR_NUMBER%TYPE,
        P_PAN_NUMBER IDENTITY_INFO.PAN_NUMBER%TYPE
    ) ;
END    IDENTITY_INFO_PKG;
/