create or replace PACKAGE UTILS_TRANSACTIONS IS

    -- Define a cursor to select all transactions
    CURSOR TRANSACTION_CURSOR IS
        SELECT * FROM TRANSACTIONS;

    -- Define a record type based on the TRANSACTIONS table
    TYPE TRANSACTION_RECORD IS RECORD (
        R_TRANSACTION_ID          TRANSACTIONS.TRANSACTION_ID%TYPE,
        R_FROM_ACCOUNT_ID         TRANSACTIONS.FROM_ACCOUNT_ID%TYPE,
        R_TO_ACCOUNT_ID           TRANSACTIONS.TO_ACCOUNT_ID%TYPE,
        R_AMOUNT                  TRANSACTIONS.AMOUNT%TYPE,
        R_TRANSACTION_TIMESTAMP   TRANSACTIONS.TRANSACTION_TIMESTAMP%TYPE,
        R_TRANSACTION_TYPE        TRANSACTIONS.TRANSACTION_TYPE%TYPE,
        R_STATUS                  TRANSACTIONS.STATUS%TYPE
    );

    -- Define an associative array type to hold transactions
    TYPE TRANSACTION_TABLE_COL IS TABLE OF TRANSACTION_RECORD INDEX BY VARCHAR2(40);

    V_TRANSACTIONS_COLLECTION TRANSACTION_TABLE_COL;

    PROCEDURE LOADER_TRANSACTIONS;

    -- Procedure to display all transactions
    PROCEDURE DISPLAY_TRANSACTIONS;

    -- Procedure to get details by transaction ID
    PROCEDURE GET_DETAILS_BY_TRANSACTION_ID(P_TRANSACTION_ID TRANSACTIONS.TRANSACTION_ID%TYPE);

    -- Procedure to get successful transactions
    PROCEDURE GET_SUCCESSFUL_TRANSACTIONS;

    -- Procedure to get unsuccessful transactions
    PROCEDURE GET_UNSUCCESSFUL_TRANSACTIONS;

    -- Procedure to get transaction status by transaction ID
    PROCEDURE GET_TRANSACTION_STATUS_BY_TRANSACTION_ID(P_TRANSACTION_ID TRANSACTIONS.TRANSACTION_ID%TYPE);

    -- Procedure to get transactions by a specific date
    PROCEDURE  GET_TRANSACTIONS_BY_DATE(P_DATE VARCHAR2);

    -- Procedure to get transactions by account ID
    PROCEDURE GET_TRANSACTION_BY_ACCOUNT_ID(P_FROM_ACCOUNT_ID TRANSACTIONS.FROM_ACCOUNT_ID%TYPE);

    -- Procedure to get deposits by account ID
    PROCEDURE GET_DEPOSIT_BY_ACCOUNT_ID(P_TO_ACCOUNT_ID TRANSACTIONS.TO_ACCOUNT_ID%TYPE);

    -- Procedure to get withdrawals by account ID
    PROCEDURE GET_WITHDRAWALS_BY_ACCOUNT_ID(P_FROM_ACCOUNT_ID TRANSACTIONS.FROM_ACCOUNT_ID%TYPE);

    -- Procedure to get transfers by account ID
    PROCEDURE GET_TRANSFER_BY_ACCOUNT_ID(P_FROM_ACCOUNT_ID TRANSACTIONS.FROM_ACCOUNT_ID%TYPE);

    -- Procedure to display all deposits
    PROCEDURE DISPLAY_DEPOSITS;

    -- Procedure to display all transfers
    PROCEDURE DISPLAY_TRANSFER;

    -- Procedure to display all withdrawals
    PROCEDURE DISPLAY_WITHDRAWAL;

    PROCEDURE GET_TRANSACTION_HISTORY_BY_ACCOUNT_ID_WITHIN_SPECIFIC_DATES(P_FROM_ACCOUNT_ID TRANSACTIONS.FROM_ACCOUNT_ID%TYPE,FROM_DATE DATE,TILL_DATE DATE);

END UTILS_TRANSACTIONS;
/