create or replace PACKAGE TRANSACTION_PKG
IS
PROCEDURE ADD_TRANSACTION
(
    P_FROM_ACCOUNT_ID_ TRANSACTIONS.FROM_ACCOUNT_ID%TYPE,
    P_TO_ACCOUNT_ID_ TRANSACTIONS.TO_ACCOUNT_ID%TYPE,
    P_AMOUNT_ TRANSACTIONS.AMOUNT%TYPE,
    P_TRANSACTION_TYPE_ TRANSACTIONS.TRANSACTION_TYPE%TYPE,
    P_STATUS_ TRANSACTIONS.STATUS%TYPE
);
END;
/