create or replace PACKAGE UTILS_SCHEDULED_TRANSFER IS

    -- Define a cursor for scheduled transfers
    CURSOR SCHEDULED_TRANSFER_CURSOR IS
        SELECT TRANSFER_ID, FROM_ACCOUNT_ID, TO_ACCOUNT_ID, AMOUNT, SCHEDULED_DATE, CREATED_AT, STATUS
        FROM SCHEDULED_TRANSFER;

    -- Define a record type to hold scheduled transfer details
    TYPE SCHEDULED_TRANSFER_RECORD_TYPE IS RECORD (
        R_TRANSFER_ID       SCHEDULED_TRANSFER.TRANSFER_ID%TYPE,
        R_FROM_ACCOUNT_ID   SCHEDULED_TRANSFER.FROM_ACCOUNT_ID%TYPE,
        R_TO_ACCOUNT_ID     SCHEDULED_TRANSFER.TO_ACCOUNT_ID%TYPE,
        R_AMOUNT            SCHEDULED_TRANSFER.AMOUNT%TYPE,
        R_SCHEDULED_DATE    SCHEDULED_TRANSFER.SCHEDULED_DATE%TYPE,
        R_CREATED_AT        SCHEDULED_TRANSFER.CREATED_AT%TYPE,
        R_STATUS            SCHEDULED_TRANSFER.STATUS%TYPE
    );

    -- Define a collection type for storing multiple scheduled transfer records
    TYPE SCHEDULED_TRANSFER_TABLE_TYPE IS TABLE OF SCHEDULED_TRANSFER_RECORD_TYPE INDEX BY VARCHAR2(40);

    -- Declare a variable to hold the scheduled transfer collection
    V_SCHEDULED_TRANSFER_COLLECTION SCHEDULED_TRANSFER_TABLE_TYPE;

    -- Procedure to load scheduled transfers into the collection
    PROCEDURE SCHEDULED_TRANSFER_LOADER;

    -- Procedure to get transfer details by transfer ID
    PROCEDURE GET_TRANSFER_DETAILS_BY_TRANSFER_ID(P_TRANSFER_ID SCHEDULED_TRANSFER.TRANSFER_ID%TYPE);

    -- Procedure to get transfer details by scheduled date
    PROCEDURE GET_TRANSFER_DETAILS_BY_DATE(P_SCHEDULED_DATE SCHEDULED_TRANSFER.SCHEDULED_DATE%TYPE);

    -- Procedure to get all completed transfers by status
    PROCEDURE GET_ALL_COMPLETED_TRANSFERS;

    -- Procedure to get all in completed transfers by status
    PROCEDURE GET_ALL_IN_COMPLETED_TRANSFERS;

    -- Procedure to get transfer status by transfer ID
    PROCEDURE GET_TRANSFER_STATUS_BY_TRANSFER_ID(P_TRANSFER_ID SCHEDULED_TRANSFER.TRANSFER_ID%TYPE);

    -- Procedure to display all scheduled transfers
    PROCEDURE DISPLAY_SCHEDULED_TRANSFER;

    --Procedure to update ammount
    PROCEDURE UPDATE_AMOUNT_TRANSFER_ID(P_TRANSFER_ID SCHEDULED_TRANSFER.TRANSFER_ID%TYPE, P_AMOUNT SCHEDULED_TRANSFER.AMOUNT%TYPE);

    --Procedure to update scheduled transfer
    PROCEDURE UPDATE_SCHEDULED_DATE_BY_TRANSFER_ID(P_TRANSFER_ID SCHEDULED_TRANSFER.TRANSFER_ID%TYPE, P_SCHEDULED_DATE SCHEDULED_TRANSFER.SCHEDULED_DATE%TYPE );
END UTILS_SCHEDULED_TRANSFER;
/