create or replace PACKAGE UTILS_SCHEDULED_TRANSFER_LOG
IS
    PROCEDURE GET_SCHEDULED_LOG_BY_TRANSFER_ID(P_TRANSFER_ID SCHEDULED_TRANSFER_LOG.TRANSFER_ID%TYPE);

    PROCEDURE GET_SCHEDULED_LOG_BY_UPDATED_DATE(P_UPDATED_DATE DATE);

    PROCEDURE GET_SCHEDULED_LOG_BY_UPDATED_DATE_RANGE(P_FROM_UPDATED_DATE DATE, P_TO_UPDATED_DATE DATE);

    PROCEDURE DISPLAY_SCHEDULED_TRANSFER_LOG;

END UTILS_SCHEDULED_TRANSFER_LOG;
/