
  CREATE TABLE "AUDIT_LOG" 
   (	"AUDIT_ID" VARCHAR2(30), 
	"ADMIN_NAME" VARCHAR2(50), 
	"OPERATION" VARCHAR2(50), 
	"TABLE_NAME" VARCHAR2(50), 
	"EXECUTED_AT" TIMESTAMP (6), 
	 PRIMARY KEY ("AUDIT_ID")
  USING INDEX  ENABLE
   ) ;