
  CREATE TABLE "EXCHANGE_CURRENCY" 
   (	"COUNTRY" VARCHAR2(50) NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(3), 
	"EXCHANGE_RATE" NUMBER(10,4) NOT NULL ENABLE, 
	 PRIMARY KEY ("CURRENCY_CODE")
  USING INDEX  ENABLE
   ) ;