
  CREATE TABLE "SCHEDULED_TRANSFER_LOG" 
   (	"TRANSFER_ID" VARCHAR2(40), 
	"UPDATED_COLUMN" VARCHAR2(40), 
	"OLD_VALUE" VARCHAR2(40), 
	"NEW_VALUE" VARCHAR2(40), 
	"UPDATED_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;