
  CREATE TABLE "TRANSACTIONS" 
   (	"TRANSACTION_ID" VARCHAR2(25), 
	"FROM_ACCOUNT_ID" VARCHAR2(40), 
	"TO_ACCOUNT_ID" VARCHAR2(40), 
	"AMOUNT" NUMBER(15,4), 
	"TRANSACTION_TIMESTAMP" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"TRANSACTION_TYPE" VARCHAR2(50), 
	"STATUS" CHAR(1), 
	 PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX  ENABLE
   ) ;