
  CREATE TABLE "USERS_LOG" 
   (	"USER_ID" VARCHAR2(40), 
	"COLUMN_CHANGED" VARCHAR2(30), 
	"OLD_VALUE" VARCHAR2(30), 
	"NEW_VALUE" VARCHAR2(30), 
	"UPDATED_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;