
  CREATE TABLE "USER_ADDRESS" 
   (	"ADDRESS_ID" VARCHAR2(40), 
	"H_NO" VARCHAR2(10) NOT NULL ENABLE, 
	"STREET" VARCHAR2(50) NOT NULL ENABLE, 
	"CITY" VARCHAR2(50) NOT NULL ENABLE, 
	"PINCODE" VARCHAR2(6) NOT NULL ENABLE, 
	"DISTRICT" VARCHAR2(50) NOT NULL ENABLE, 
	"STATE" VARCHAR2(50) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(50) NOT NULL ENABLE, 
	 PRIMARY KEY ("ADDRESS_ID")
  USING INDEX  ENABLE
   ) ;