create or replace PACKAGE UTILS_ACCOUNT_LOG IS 

    PROCEDURE GET_ACCOUNTS_LOG_BY_ACCOUNT_ID(P_ACCOUNT_ID ACCOUNT_LOG.ACCOUNT_ID%TYPE);

    PROCEDURE GET_ACCOUNTS_LOG_BY_UPDATED_DATE(P_UPDATED_DATE DATE);

    PROCEDURE GET_ACCOUNTS_LOG_BY_DATE_RANGE(P_FROM_UPDATED_DATE DATE, P_TO_UPDATED_DATE DATE);

    PROCEDURE DISPLAY_ACCOUNTS_LOG;

END UTILS_ACCOUNT_LOG;
/