create or replace PACKAGE USER_PKG
IS
    TYPE IDENTITY_RECORD_TYPE IS RECORD(
        AADHAR IDENTITY_INFO.AADHAR_NUMBER%TYPE,
        PAN IDENTITY_INFO.PAN_NUMBER%TYPE
    );
    FUNCTION CHECK_AADHAR_EXISTS(AADHAR IN VARCHAR2) RETURN BOOLEAN;
    FUNCTION CHECK_PAN_EXISTS(pan IN VARCHAR2) RETURN BOOLEAN;
    FUNCTION VALIDATE_AADHAR(P_AADHAR_NUMBER VARCHAR2) RETURN BOOLEAN;
    FUNCTION VALIDATE_PAN(P_PAN_NUMBER IN VARCHAR2) RETURN BOOLEAN;
    FUNCTION VALIDATE_DOB(dateObirth date) RETURN BOOLEAN; 
    FUNCTION VALIDATE_EMAIL(email VARCHAR2) RETURN BOOLEAN;
    FUNCTION VALIDATE_PHONE_NUMBER(PHONE VARCHAR2) RETURN BOOLEAN;
    FUNCTION GET_ADDRESS_ID( 
        P_H_NO	VARCHAR2, 
        P_STREET VARCHAR2, 
        P_CITY VARCHAR2,	
        P_PINCODE VARCHAR2,	
        P_DISTRICT	VARCHAR2, 
        P_STATE	VARCHAR2, 
        P_COUNTRY VARCHAR2
    ) RETURN VARCHAR2;

    FUNCTION CHECK_NULL_USERS(
        P_FIRST_NAME_    USERS.FIRST_NAME%TYPE,
        P_LAST_NAME_     USERS.LAST_NAME%TYPE,
        P_PHONE_NUMBER_  USERS.PHONE_NUMBER%TYPE,
        P_EMAIL_         USERS.EMAIL%TYPE,
        P_DOB_           USERS.DOB%TYPE,
        P_GENDER_        USERS.GENDER%TYPE,
        P_AADHAR_NUMBER_ USERS.AADHAR_NUMBER%TYPE,
        P_PAN_NUMBER_    USERS.PAN_NUMBER%TYPE,
        P_H_NO_          USER_ADDRESS.H_NO%TYPE,
        P_STREET_        USER_ADDRESS.STREET%TYPE,
        P_CITY_          USER_ADDRESS.CITY%TYPE,
        P_PINCODE_       USER_ADDRESS.PINCODE%TYPE,
        P_DISTRICT_      USER_ADDRESS.DISTRICT%TYPE,
        P_STATE_         USER_ADDRESS.STATE%TYPE,
        P_COUNTRY_       USER_ADDRESS.COUNTRY%TYPE
    ) 
    RETURN BOOLEAN;

    FUNCTION GET_AADHAR_PAN_FROM_IDENTITY_INFO( AADHAR IDENTITY_INFO.AADHAR_NUMBER%TYPE ) 
    RETURN USER_PKG.IDENTITY_RECORD_TYPE;

    PROCEDURE ADD_USER
        (
            P_FIRST_NAME	USERS.FIRST_NAME%TYPE,
         	P_LAST_NAME	USERS.LAST_NAME%TYPE,
         	P_PHONE_NUMBER	USERS.PHONE_NUMBER%TYPE,
         	P_EMAIL	USERS.EMAIL%TYPE,
            P_DOB	USERS.DOB%TYPE,
            P_GENDER USERS.GENDER%TYPE,
         	P_AADHAR_NUMBER	USERS.AADHAR_NUMBER%TYPE,
         	P_PAN_NUMBER	USERS.PAN_NUMBER%TYPE,

            P_H_NO	USER_ADDRESS.H_NO%TYPE,
         	P_STREET	USER_ADDRESS.STREET%TYPE,
         	P_CITY	USER_ADDRESS.CITY%TYPE,
         	P_PINCODE USER_ADDRESS.PINCODE%TYPE,
         	P_DISTRICT	USER_ADDRESS.DISTRICT%TYPE,
         	P_STATE	USER_ADDRESS.STATE%TYPE,
         	P_COUNTRY	USER_ADDRESS.COUNTRY%TYPE
        );
END USER_PKG;
/