create or replace PACKAGE UTILS_USERS IS
    TYPE USERS_RECORD_TYPE IS RECORD (
        R_USER_ID         USERS.USER_ID%TYPE,
        R_FIRST_NAME      USERS.FIRST_NAME%TYPE,
        R_LAST_NAME       USERS.LAST_NAME%TYPE,
        R_PHONE_NUMBER    USERS.PHONE_NUMBER%TYPE,
        R_EMAIL           USERS.EMAIL%TYPE,
        R_DOB             USERS.DOB%TYPE,
        R_GENDER          USERS.GENDER%TYPE,
        R_AADHAR_NUMBER   USERS.AADHAR_NUMBER%TYPE,
        R_PAN_NUMBER      USERS.PAN_NUMBER%TYPE,
        R_ADDRESS_ID      USERS.ADDRESS_ID%TYPE
    );
    TYPE USER_COL_TYPE IS TABLE OF USERS_RECORD_TYPE INDEX BY VARCHAR2(40);

    V_USERS USER_COL_TYPE;

    CURSOR USERS_CURSOR IS SELECT * FROM USERS;

    PROCEDURE LOADER_USERS;
    PROCEDURE DISPLAY_USERS;
    FUNCTION  CHECK_USER_ID_EXISTS(P_USER_ID USERS.USER_ID%TYPE) RETURN BOOLEAN;
    PROCEDURE GET_USERS_DETAILS_BY_USER_ID(P_USER_ID  USERS.USER_ID%TYPE);
    PROCEDURE GET_USER_DETAILS_BY_PAN_NUMBER(P_PAN_NUMBER  USERS.PAN_NUMBER%TYPE);
    PROCEDURE GET_USER_DETAILS_BY_PHONE_NUMBER(P_PHONE_NUMBER  USERS.PHONE_NUMBER%TYPE);
    PROCEDURE GET_USER_DETAILS_BY_AADHAR_NUMBER(P_AADHAR_NUMBER  USERS.AADHAR_NUMBER%TYPE);
    PROCEDURE GET_USERS_BY_GENDER(P_GENDER USERS.GENDER%TYPE);
    PROCEDURE GET_USER_DETAILS_BY_ADDRESS_ID(P_ADDRESS_ID USERS.ADDRESS_ID%TYPE);     
    PROCEDURE GET_ADDRESS_BY_USER_ID(P_USER_ID USERS.USER_ID%TYPE);
    PROCEDURE UPDATE_EMAIL_BY_USER_ID(P_USER_ID USERS.USER_ID%TYPE, P_EMAIL USERS.EMAIL%TYPE);
    PROCEDURE UPDATE_PHONE_NUMBER_BY_USER_ID(P_USER_ID USERS.USER_ID%TYPE, P_PHONE_NUMBER USERS.PHONE_NUMBER%TYPE);
    PROCEDURE UPDATE_ADDRESS_BY_USER_ID(P_USER_ID USERS.USER_ID%TYPE, P_ADDRESS_ID USERS.ADDRESS_ID%TYPE);
    PROCEDURE GET_USER_DETAILS_BY_CITY(P_CITY USER_ADDRESS.CITY%TYPE);
    PROCEDURE GET_USER_DETAILS_BY_DISTRICT(P_DISTRICT USER_ADDRESS.DISTRICT%TYPE);
    PROCEDURE UPDATE_FIRST_NAME_BY_USER_ID(P_USER_ID USERS.USER_ID%TYPE, P_FIRST_NAME USERS.FIRST_NAME%TYPE); 
    PROCEDURE UPDATE_LAST_NAME_BY_USER_ID(P_USER_ID USERS.USER_ID%TYPE, P_LAST_NAME USERS.LAST_NAME%TYPE);

END UTILS_USERS;
/