create or replace PACKAGE CURRENCY_PKG IS
    FUNCTION VALIDATE_COUNTRY(P_COUNTRY_NAME VARCHAR2) RETURN BOOLEAN;
    FUNCTION VALIDATE_CURRENCY_CODE(P_CURRENCY VARCHAR2) RETURN BOOLEAN;
    FUNCTION CHECK_COUNTRY_EXISTS(P_COUNTRY IN OUT EXCHANGE_CURRENCY.COUNTRY%TYPE) RETURN BOOLEAN;
    FUNCTION CHECK_CURRENCY_CODE_EXISTS(P_CURRENCY_CODE IN OUT EXCHANGE_CURRENCY.CURRENCY_CODE%TYPE) RETURN BOOLEAN;
    PROCEDURE  ADD_CURRENCY
        (
            P_COUNTRY IN  EXCHANGE_CURRENCY.COUNTRY%TYPE,
            P_CURRENCY_CODE IN EXCHANGE_CURRENCY.CURRENCY_CODE%TYPE,
            P_EXCHANGE_RATE EXCHANGE_CURRENCY.EXCHANGE_RATE%TYPE
        );
    FUNCTION CHECK_NULLS_ADD_CURRENCY
        (
            P_COUNTRY_   EXCHANGE_CURRENCY.COUNTRY%TYPE,
            P_CURRENCY_CODE_  EXCHANGE_CURRENCY.CURRENCY_CODE%TYPE,
            P_EXCHANGE_RATE_ EXCHANGE_CURRENCY.EXCHANGE_RATE%TYPE
        ) RETURN BOOLEAN;
END CURRENCY_PKG;
/