create or replace PACKAGE RECURRING_PAYMENT_PKG IS
    FUNCTION CHECK_NULLS_ADD_RECURRING_PAYMENT (
        P_FROM_ACCOUNT_ID_ RECURRING_PAYMENT.FROM_ACCOUNT_ID%TYPE,
        P_TO_ACCOUNT_ID_ RECURRING_PAYMENT.TO_ACCOUNT_ID%TYPE,
        P_AMOUNT_ RECURRING_PAYMENT.AMOUNT %TYPE,
        P_INTERVAL_DAYS_ RECURRING_PAYMENT.INTERVAL_DAYS%TYPE,
        P_END_DATE_ RECURRING_PAYMENT.END_DATE%TYPE
    ) 
    RETURN BOOLEAN ;
    PROCEDURE ADD_RECURRING_PAYMENT
    (
        P_FROM_ACCOUNT_ID RECURRING_PAYMENT.FROM_ACCOUNT_ID%TYPE,
        P_TO_ACCOUNT_ID RECURRING_PAYMENT.TO_ACCOUNT_ID%TYPE,
        P_AMOUNT RECURRING_PAYMENT.AMOUNT %TYPE,
        P_INTERVAL_DAYS RECURRING_PAYMENT.INTERVAL_DAYS%TYPE,
        P_END_DATE RECURRING_PAYMENT.END_DATE%TYPE
    );
END RECURRING_PAYMENT_PKG;
/