create or replace PROCEDURE ACCOUNT_AGGREGATION(P_USER_ID USERS.USER_ID%TYPE)
IS
    CURSOR ACCOUNT_AGGREGATION_CURSOR IS
        SELECT * FROM ACCOUNT WHERE USER_ID = P_USER_ID;
    V_USER_ID USERS.USER_ID%TYPE := NULL;
    USER_TOTAL_BALANCE ACCOUNT.BALANCE%TYPE := 0;
    CONVERTED_BALANCE ACCOUNT.BALANCE%TYPE;
BEGIN
    SELECT USER_ID INTO V_USER_ID FROM USERS WHERE USER_ID = P_USER_ID;
    IF V_USER_ID IS NULL THEN
        RAISE NO_DATA_FOUND;
    ELSE
        DBMS_OUTPUT.PUT_LINE('ACCOUNTS OF THE USER ' || P_USER_ID);
        DBMS_OUTPUT.PUT_LINE(RPAD('-',90,'-'));
        DBMS_OUTPUT.PUT_LINE
            (
                RPAD('USER_ID', 18) || 
                RPAD('ACCOUNT_ID', 18) ||
                RPAD('BALANCE', 18) ||
                RPAD('CURRENCY_CODE', 18) ||
                RPAD('CONVERTED_BALANCE', 18)
            );
        DBMS_OUTPUT.PUT_LINE(RPAD('-',90,'-'));
        FOR I_ACCOUNT_AGGREGATION_CURSOR IN ACCOUNT_AGGREGATION_CURSOR
        LOOP
            CONVERTED_BALANCE := CURRENCY_CONVERTER_FUNC
                                    (
                                        FROM_CURRENCY_CODE => I_ACCOUNT_AGGREGATION_CURSOR.CURRENCY_CODE,
                                        TO_CURRENCY_CODE => 'INR',
                                        FROM_CURRENCY_VALUE => I_ACCOUNT_AGGREGATION_CURSOR.BALANCE
                                    );
            USER_TOTAL_BALANCE := USER_TOTAL_BALANCE + CONVERTED_BALANCE;
            
            DBMS_OUTPUT.PUT_LINE
            (
                RPAD(I_ACCOUNT_AGGREGATION_CURSOR.USER_ID, 18) || 
                RPAD(I_ACCOUNT_AGGREGATION_CURSOR.ACCOUNT_ID, 18) ||
                RPAD(I_ACCOUNT_AGGREGATION_CURSOR.BALANCE, 18) ||
                RPAD(I_ACCOUNT_AGGREGATION_CURSOR.CURRENCY_CODE, 18) ||
                RPAD(CONVERTED_BALANCE, 18)
            );
        END LOOP;
        DBMS_OUTPUT.PUT_LINE(RPAD('-',90,'-'));
        DBMS_OUTPUT.PUT_LINE(LPAD('THE TOTAL BALANCE OF THE USER: ' || P_USER_ID || ' FROM DIFFERENT ACCOUNTS IS: ' || USER_TOTAL_BALANCE, 81));
    END IF;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                DBMS_OUTPUT.PUT_LINE('NO USER WITH THE USER ID: ' || P_USER_ID);
    
END ACCOUNT_AGGREGATION;
/